version: '3.8'
services:
    oai-gnb:
        image: oai-gnb-aw2s:latest
          #image: default-route-openshift-image-registry.apps.oai.cs.eurecom.fr/oaicicd-ran/oai-gnb-aw2s:develop
        privileged: true
        container_name: oai-gnb
          #entrypoint: /bin/bash -c "sleep infinity"
        environment:
            TZ: Europe/Paris
            USE_VOLUMED_CONF: 'yes'
            USE_ADDITIONAL_OPTIONS: --sa
        volumes:
            - ../conf_files/gnb.sa.band78.51prb.aw2s.dddsu.conf:/opt/oai-gnb-aw2s/etc/mounted.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            core-net:
                ipv4_address: 192.168.70.150
            aw2s:
                ipv4_address: 192.168.80.2
networks:
    core-net:
        external:
            name: demo-oai-public-net
    aw2s:
        name: aw2s
        driver: macvlan
        driver_opts:
            parent: eno12399np0
        ipam:
            config:
                - subnet: "192.168.80.0/24"
                  ip_range: "192.168.80.0/26"
                  gateway: "192.168.80.1"
